In [125]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [126]:
df = pd.read_csv('C:/Users/skych/Desktop/Python/Churn_Modelling.csv')

In [127]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age   
0             1    15634602   Hargrave          619    France  Female   42  \
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember   
0          2       0.00              1          1               1  \
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [128]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [129]:
x=df.iloc[:,3:-1].values
y=df.iloc[:,-1].values
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [130]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])
x[:,2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

In [131]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x  = np.array(ct.fit_transform(x))

In [132]:
x[:1]

array([[1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88]],
      dtype=object)

In [133]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=1)
x_train

array([[0.0, 1.0, 0.0, ..., 0, 1, 124749.08],
       [1.0, 0.0, 0.0, ..., 0, 0, 41104.82],
       [0.0, 1.0, 0.0, ..., 1, 1, 45750.21],
       ...,
       [1.0, 0.0, 0.0, ..., 1, 1, 92027.69],
       [1.0, 0.0, 0.0, ..., 1, 1, 101168.9],
       [0.0, 1.0, 0.0, ..., 1, 0, 33462.94]], dtype=object)

In [134]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [135]:
ann = tf.keras.Sequential()

In [136]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [137]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy')

In [138]:
ann.fit(x_train, y_train, batch_size = 20, epochs= 30)

Epoch 1/30
400/400 [==============================] - 1s 956us/step - loss: 0.5715 - accuracy: 0.7139
Epoch 2/30
400/400 [==============================] - 0s 721us/step - loss: 0.4431 - accuracy: 0.8095
Epoch 3/30
400/400 [==============================] - 0s 812us/step - loss: 0.4089 - accuracy: 0.8266
Epoch 4/30
400/400 [==============================] - 0s 647us/step - loss: 0.3833 - accuracy: 0.8426
Epoch 5/30
400/400 [==============================] - 0s 656us/step - loss: 0.3687 - accuracy: 0.8486
Epoch 6/30
400/400 [==============================] - 0s 728us/step - loss: 0.3619 - accuracy: 0.8518
Epoch 7/30
400/400 [==============================] - 0s 738us/step - loss: 0.3579 - accuracy: 0.8539
Epoch 8/30
400/400 [==============================] - 0s 860us/step - loss: 0.3560 - accuracy: 0.8539
Epoch 9/30
400/400 [==============================] - 0s 818us/step - loss: 0.3539 - accuracy: 0.8546
Epoch 10/30
400/400 [==============================] - 0s 770us/step - loss: 0.353

In [155]:
ann.evaluate(x_train, y_train)

250/250 [==============================] - 0s 761us/step - loss: 0.3332 - accuracy: 0.8636


[0.33323466777801514, 0.8636249899864197]

In [156]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

63/63 [==============================] - 0s 636us/step
[[1536   49]
 [ 225  190]]
0.863


In [199]:
result = ann.predict(sc.transform([[1, 0, 1, 600, 2, 45, 6, 40000, 1, 1, 1, 100000]]))
print(result)
if result < 0.5:
    print('Stayed')
else:
    print('Left')

1/1 [==============================] - 0s 19ms/step
[[0.09518194]]
Stayed
